# Generated by Django 4.1.7 on 2023-03-18 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_NewsSite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='ParentCommentID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='_NewsSite.comments'),
        ),
    ]
