# Generated by Django 4.1.7 on 2023-03-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_NewsSite', '0003_postcategory_posts_datee_alter_comments_datee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='Text',
            field=models.CharField(max_length=10000),
        ),
    ]
