# Generated by Django 4.1.7 on 2023-04-04 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_NewsSite', '0004_alter_posts_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='ParentCommentID',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='_NewsSite.comments'),
        ),
    ]
