# Generated by Django 4.1.7 on 2023-04-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_NewsSite', '0005_alter_comments_parentcommentid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['Datee'], 'verbose_name': 'Коментарии'},
        ),
        migrations.AlterModelOptions(
            name='postcategory',
            options={'ordering': ['category'], 'verbose_name': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['Datee'], 'verbose_name': 'Посты'},
        ),
        migrations.AlterModelOptions(
            name='userphoto',
            options={'verbose_name': 'Аватарки'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['date_create'], 'verbose_name': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
