# Generated by Django 4.1.7 on 2023-04-15 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_NewsSite', '0007_remove_users_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('Login', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('is_blocked', models.BooleanField(default=False)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Пользователи',
                'ordering': ['date_create'],
            },
        ),
        migrations.AlterField(
            model_name='comments',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_NewsSite.myusers'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='UserID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='_NewsSite.myusers'),
        ),
        migrations.AlterField(
            model_name='userphoto',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='_NewsSite.myusers'),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
