# Generated by Django 4.1.7 on 2023-04-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_NewsSite', '0008_myusers_alter_comments_userid_alter_posts_userid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='Login',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
